---
- project:
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8
        - kayobe-seed-centos8

    gate:
      queue: kayobe
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8
        - kayobe-seed-centos8
