---
- project:
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8
        - kayobe-overcloud-tls-centos8
        - kayobe-overcloud-host-configure-centos8
        - kayobe-overcloud-upgrade-centos8
        - kayobe-seed-centos8
        - kayobe-seed-upgrade-centos8
        - kayobe-seed-vm-centos8

    gate:
      queue: kayobe
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8
        - kayobe-overcloud-tls-centos8
        - kayobe-overcloud-host-configure-centos8
        - kayobe-overcloud-upgrade-centos8
        - kayobe-seed-centos8
        - kayobe-seed-upgrade-centos8
        - kayobe-seed-vm-centos8
